# Generated by Django 4.2.6 on 2023-11-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_ct'),
    ]

    operations = [
        migrations.AddField(
            model_name='ct',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
