# Generated by Django 4.2.6 on 2023-11-13 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_ct_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
