# Generated by Django 4.2.6 on 2023-11-13 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_delete_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ct',
            new_name='contact',
        ),
    ]
