# Generated by Django 4.2.6 on 2023-11-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_alter_band_year_formed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='biography',
            field=models.CharField(default='Biographie indisponible', max_length=1000),
        ),
        migrations.AlterField(
            model_name='band',
            name='genre',
            field=models.CharField(choices=[('HH', 'Hip Hop'), ('SP', 'Synth Pop'), ('AR', 'Alternative Rock')], default='pas de genre specifié', max_length=5),
        ),
    ]
