# Generated by Django 4.2.6 on 2023-11-22 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_listing_band'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='listing',
            new_name='Annonce',
        ),
    ]
